// app/src/lib/components/ui/Badge.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import type { Snippet } from 'svelte';

	type Variant = 'brand' | 'ok' | 'warn' | 'muted' | 'danger';

	let {
		variant = 'muted',
		class: className = '',
		children
	}: { variant?: Variant; class?: string; children?: Snippet } = $props();

	const variants: Record<Variant, string> = {
		brand: 'border-[#ffd40040] text-brand',
		ok: 'border-emerald-400/40 text-emerald-300',
		warn: 'border-amber-400/40 text-amber-300',
		danger: 'border-red-400/40 text-red-300',
		muted: 'border-white/15 text-white/60'
	};
</script>

<span
	class={cn(
		'inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium',
		variants[variant],
		className
	)}
>
	{@render children?.()}
</span>

// web/src/components/ui/badge.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const badgeVariants = cva(
  "inline-flex items-center justify-center rounded-md border px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 gap-1 [&>svg]:size-3 [&>svg]:pointer-events-none transition-colors overflow-hidden",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground",
        destructive:
          "border-transparent bg-destructive/15 text-destructive border-destructive/30",
        outline: "text-foreground",
        ok: "border-transparent bg-[var(--ok)]/15 text-[var(--ok)] border-[var(--ok)]/25",
        warn: "border-transparent bg-[var(--warn)]/15 text-[var(--warn)] border-[var(--warn)]/25",
        info: "border-transparent bg-[var(--info)]/15 text-[var(--info)] border-[var(--info)]/25",
        muted: "border-border bg-muted text-muted-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

function Badge({
  className,
  variant,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot : "span";
  return (
    <Comp
      data-slot="badge"
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  );
}

export { Badge, badgeVariants };
